//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineVoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voter
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserUsername { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> UserCountry { get; set; }
        public Nullable<int> UserGender { get; set; }
        public Nullable<int> UserAge { get; set; }
        public Nullable<bool> isAdmin { get; set; }
    }
}
