//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineVoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int VoteID { get; set; }
        public Nullable<int> User_Key { get; set; }
        public Nullable<int> Voting_Key { get; set; }
        public Nullable<int> Option_Key { get; set; }
        public string session_key { get; set; }
        public string User_name { get; set; }
    }
}
