//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineVoting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voting
    {
        public int VotingID { get; set; }
        public string VotingName { get; set; }
        public Nullable<int> VotingCategoryKEY { get; set; }
        public string QuestionLine { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> VCategoryID { get; set; }
        public string VCategoryName { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> YesOrNo { get; set; }
        public Nullable<int> YesAmount { get; set; }
        public Nullable<int> NoAmount { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
